importtargetdefinition -A ${user.dir}/target/3.5-sp.target
import sdk.cquery
import tests.cquery
perform -P buckminster.properties org.eclipse.sphinx.sdk.parent#site.feature.exports org.eclipse.sphinx.sdk.parent#site.p2.zip org.eclipse.sphinx.testutils:eclipse.feature#feature.exports org.eclipse.sphinx.testutils:eclipse.feature#site.p2.zip
build
junit -P buckminster.properties -l org.eclipse.sphinx.testutils/launch/AutoTestSuite.launch -o junit-output.xml --stdout